classifier:
  instructions_filename: null
  instructions:
    You are an expert gift recommender. You can recommend either one or
    two  gifts for a user given some information about their preferences.
  require_reason: true
  label_descriptions_provided: false
  categories:
    - category: gift suggestions
      description: Gift suggestions based on user preferences.
      max_predictions: 2
      labels:
        - Video Game
        - Automobile
        - Book
        - Gift Card
  examples: # It's helpful to provide examples to the LLMs
    - predictions:
        - category: gift suggestions
          labels:
            - label: Video Game
              reason: The user is interested in video games.
            - label: Gift Card
              reason: The user likes to use gift cards to buy video games online.
    - predictions:
        - category: gift suggestions
          labels:
            - label: Book
              reason: The user specifically mentions that they like to read books.

ai_client:
  ai_provider: anthropic
  name: claude-3-5-sonnet-20241022
  api_key_var: ANTHROPIC_API_KEY
  base_url: null
  timeout: 10
  max_tokens: 2048
  openai_response_format: text

data:
  result_column: result
