classifier:
  instructions_filename: instructions.txt
  instructions: null
  require_reason: false
  label_descriptions_provided: false
  categories:
    - category: age_group
      description: Most suitable age group for the book.
      max_predictions: 1
      labels:
        - children
        - adults
    - category: gender
      description: Most suitable gender(s) group for the book.
      max_predictions: 2
      labels:
        - male
        - female
  examples:
    - predictions:
        - category: age_group
          labels:
            - adults
        - category: gender
          labels:
            - male
            - female

ai_client:
  ai_provider: gemini
  name: gemini-1.5-flash
  api_key_var: GEMINI_API_KEY
  base_url: null # Default value used when not provided
  timeout: 10
  max_tokens: 4096

data:
  result_column: result
